site_name: Apuntes
site_url: https://github.com/garmarcj/DAM-PI-20262027
site_author: Cristian Garcia
theme:
  name: material
  language: es
  palette:
    scheme: default
    primary: red
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.integrate
nav:
  - Inicio: index.md
  - Unidad 1: unidad1.md
  - Unidad 2: unidad2.md
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
extra_css:
  - stylesheets/extra.css
use_directory_urls: false
